#!/bin/zsh
set -eu
# Installs LaunchAgent so the Telegram bot starts at login and restarts on crash.
# Uses a launcher under ~/.config (not Desktop) because LaunchAgents often get
# Operation not permitted for getcwd + script read when WorkingDirectory lies
# under Desktop/Documents (TCC).

REPO_ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
AGENT_SCRIPTS="${REPO_ROOT}/tools/obsidian-head-agent/scripts"
RUN_SCRIPT="${AGENT_SCRIPTS}/run_real_vault_bot.sh"
BOT_PY="${AGENT_SCRIPTS}/telegram_obsidian_bot.py"
CONFIG_JSON="${REPO_ROOT}/tools/obsidian-head-agent/assets/telegram-bot-config.real-vault.json"
CONFIG_DIR="${HOME}/.config/obsidian-head-agent"
LAUNCHER="${CONFIG_DIR}/start_bot.sh"
PLIST_DEST="${HOME}/Library/LaunchAgents/com.obsidian-head-agent.bot.plist"
LOG_FILE="${HOME}/Library/Logs/obsidian-head-agent-bot.log"

if [[ ! -f "$RUN_SCRIPT" ]]; then
  echo "Missing $RUN_SCRIPT" >&2
  exit 1
fi
if [[ ! -f "$BOT_PY" ]]; then
  echo "Missing $BOT_PY" >&2
  exit 1
fi

PYTHON_BIN="$(command -v python3)"
if [[ -z "$PYTHON_BIN" ]]; then
  echo "python3 not found in PATH" >&2
  exit 1
fi

mkdir -p "$CONFIG_DIR" "$(dirname "$PLIST_DEST")"
touch "$LOG_FILE"

# Resolve env path: prefer legacy location from run_real_vault_bot.sh
ENV_LEGACY="${HOME}/.config/obsidian-head-agent/telegram.env"
if [[ ! -f "$ENV_LEGACY" ]]; then
  echo "Missing telegram env. Create: $ENV_LEGACY (see run_real_vault_bot.sh)." >&2
  exit 1
fi

cat > "$LAUNCHER" <<EOF
#!/bin/zsh
set -eu
# Generated by install_launchagent.sh — rerun that script after moving the repo.
export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:\${HOME}/.local/bin:\${PATH}"
ENV_FILE="${ENV_LEGACY}"
CONFIG="${CONFIG_JSON}"
PYTHON_BIN="${PYTHON_BIN}"
BOT_PY="${BOT_PY}"
if [[ ! -f "\$ENV_FILE" ]]; then
  echo "Missing env: \$ENV_FILE" >&2
  exit 1
fi
if [[ ! -f "\$CONFIG" ]]; then
  echo "Missing config: \$CONFIG" >&2
  exit 1
fi
source "\$ENV_FILE"
exec "\$PYTHON_BIN" "\$BOT_PY" run "\$CONFIG"
EOF
chmod +x "$LAUNCHER"

cat > "$PLIST_DEST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.obsidian-head-agent.bot</string>
	<key>ProgramArguments</key>
	<array>
		<string>/bin/zsh</string>
		<string>-f</string>
		<string>${LAUNCHER}</string>
	</array>
	<key>WorkingDirectory</key>
	<string>${CONFIG_DIR}</string>
	<key>RunAtLoad</key>
	<true/>
	<key>KeepAlive</key>
	<true/>
	<key>StandardOutPath</key>
	<string>${LOG_FILE}</string>
	<key>StandardErrorPath</key>
	<string>${LOG_FILE}</string>
</dict>
</plist>
PLIST

launchctl bootout "gui/$(id -u)" "$PLIST_DEST" 2>/dev/null || launchctl unload "$PLIST_DEST" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST_DEST" 2>/dev/null || launchctl load "$PLIST_DEST"

echo "Installed LaunchAgent: $PLIST_DEST"
echo "Launcher: $LAUNCHER"
echo "Logs: $LOG_FILE"
echo "Tip: if the bot still exits, grant Full Disk Access to Terminal (or python3) or move the repo off Desktop."
